### ISSUE TITLE
Review what code should live in components directory

### ISSUE THREAD

**Issue by bluefuton** [annacmc/records-meter#9]
The current component `BarChart` makes a lot of sense, but `Auth` and `getFeeds` don't feel like they belong there.

Let's have a think about how the output is structured:
App
  - Title
  - Record count and current plan limit ("23 records out of an allotted 1000")
  - Bar chart and key

There might also be some error states that need a message box to be displayed.

So a simple App.js' `render()` might look a bit like:

```
return (
      <main>
        <h1>{ translate( 'Fantastic bar chart' ) }</h1>
        <RecordCount recordCount={ 50 } planRecordLimit={ 1000 } />
        <BarChart data={this.state.feed[0]} />
      </main>
    );
```

Potentially we could move the functionality you have in `Auth` and `getFeeds` into a separate `lib/` folder.

**Comment by annacmc** [comment]
Sure, this makes a lot of sense. The Auth component was leftover from times passed, where I was trying to oAuth. For now, I've removed it completely. 

I've also restructured a bunch, moving the getFeeds into a /lib/ directory, and created a RecordCount component to separate the text from the chart. 

fixed in https://github.com/annacmc/records-meter/commit/a3ade1a329b0dbfac412e1c2250d5dc70f2f6a6e
